apiVersion: v2
appVersion: 1.12.3
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
keywords:
- ingress
- nginx
kubeVersion: '>=1.21.0-0'
maintainers:
- name: nanaki-93
name: nginx
version: 1.0.0
