apiVersion: v2
appVersion: v3.0.6
kubeVersion: ">=1.25.0-0"
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 1.0.0
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: nanaki-93