apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test-app
  labels:
    app: test-app-argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-argo
  template:
    metadata:
      labels:
        app: test-app-argo
    spec:
      containers:
        - name: test-app
          image: d-reg.aki.local/test-app-argo:v1  # Update with your image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "1.0.0"

---
apiVersion: v1
kind: Service
metadata:
  name: test-app-argo-service
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP